### ISSUE TITLE
Code verifier too short

### ISSUE THREAD

**Issue by JurRutten** [tonyxu-io/pkce-generator#2]
Your code is not generating a code verifier that is long enough, the RFC requiers a minimum of 43 characters.

code_verifier = high-entropy cryptographic random STRING using the
  unreserved characters [A-Z] / [a-z] / [0-9] / “-” / “.” / “_” / “~”
  from Section 2.3 of [RFC3986], with a minimum length of 43 characters
  and a maximum length of 128 characters.

**Comment by tonyxu-io** [comment]
Hi, I'm very sorry that I fixed this issue back when I first saw this issue, but forgot to update here. Please check it out and it should have longer length now.
