### ISSUE TITLE
Code verifier and code challenge terms need to be interchanged

### ISSUE THREAD

**Issue by mefarazath** [tonyxu-io/pkce-generator#3]
Hi @tonyxu-io,

First of all thanks a lot for hosting this tool. It makes life so much easier when testing the PKCE flows.

When a read through https://tools.ietf.org/html/rfc7636, a small question came into my mind. In the tool, 

![image](https://user-images.githubusercontent.com/5237653/66713185-f87faa80-edc4-11e9-94d7-d594c0132376.png)

The **code challenge** seems to be a 43 character random string and the code verifier is the base64URLencoded value of the sha256 hash of the **code challenge**. 

However, the spec https://tools.ietf.org/html/rfc7636 defines the two terms/names in the opposite way.

ie. code verifier  is the 43 - 128 character random string (https://tools.ietf.org/html/rfc7636#section-4.1)

code challenge is the transformation of the code verifier (https://tools.ietf.org/html/rfc7636#section-4.2)

Is this understanding correct? Should we fix the interchange the name of the two values in tool?

**Comment by mefarazath** [comment]
Looking at the code understood that code verifier you are creating is 128 :)

**Comment by tonyxu-io** [comment]
Cool, let me know if you have other question. Thanks for sharing your feedback.
